name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 100

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows]
        architecture: [x64]
        include:
          # 32-bit scipy wheels are currently only available on PyPI for Python 3.8 and 3.9
          - python-version: "3.8"
            os: windows
            architecture: x86
          - python-version: "3.9"
            os: windows
            architecture: x86

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
      - name: Install x86 packages
        if: ${{ matrix.architecture == 'x86' }}
        run: python -m pip install scipy==1.9.1 contourpy==1.0.7
      - name: Install package
        run: python -m pip install --upgrade --editable .[tests]
      - name: Run tests
        run: python -m pytest
